/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaces;

import com.graph.AlgorithmSelectionListener;
import com.graph.BranchListener;
import com.graph.LinkedList;
import com.graph.NetworkTrain;
import com.graph.PanelChangeListener;
import com.graph.Station;

/**
 *
 * @author Joao
 */
public class ShowTotalCoverage extends javax.swing.JPanel implements AlgorithmSelectionListener, BranchListener {

    private PanelChangeListener listener; // Referencia al listener
    private GUI gui;
    private boolean selectedAlgorithm;

    /**
     * Creates new form Page5
     */
    public ShowTotalCoverage(PanelChangeListener listener, GUI gui) {
        this.listener = listener;
        // Registra este panel como un listener
        gui.addAlgorithmSelectionListener(this);
        gui.addBranchListener(this);
        this.gui = gui;
        initComponents();

    }

    @Override
    public void onAlgorithmSelected(boolean useBFS) {
        this.selectedAlgorithm = useBFS;
        showTotalCoverage();
    }

    @Override
    public void onBranchChanged() {
        // Lógica para actualizar la cobertura total cuando cambian las sucursales
        showTotalCoverage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectDFSButton = new javax.swing.JButton();
        selectBFSButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTotalCoverage = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(153, 153, 153));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 20));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona un algoritmo:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cobertura total:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 20));

        selectDFSButton.setText("DFS");
        selectDFSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDFSButtonActionPerformed(evt);
            }
        });
        jPanel3.add(selectDFSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, -1));

        selectBFSButton.setText("BFS");
        selectBFSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBFSButtonActionPerformed(evt);
            }
        });
        jPanel3.add(selectBFSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        inputTotalCoverage.setColumns(20);
        inputTotalCoverage.setRows(5);
        jScrollPane1.setViewportView(inputTotalCoverage);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 210, 60));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        if (listener != null) {
            // Asegúrate de tener una instancia de Page5
            Page2 page2 = new Page2(gui, listener); // O usa una referencia existente si ya fue creada

            listener.onChangePanel(page2); // Llama al método para cambiar a Page2
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void selectDFSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDFSButtonActionPerformed
        selectedAlgorithm = false;
        gui.notifyAlgorithmSelection(selectedAlgorithm); // Notificar selección
        showTotalCoverage();
    }//GEN-LAST:event_selectDFSButtonActionPerformed

    private void selectBFSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBFSButtonActionPerformed
        selectedAlgorithm = true;
        gui.notifyAlgorithmSelection(selectedAlgorithm); // Notificar selección
        showTotalCoverage();
    }//GEN-LAST:event_selectBFSButtonActionPerformed

    private void showTotalCoverage() {
        boolean isFullyCovered = gui.checkTotalCoverage();
        if (isFullyCovered) {
            inputTotalCoverage.setText("Totalmente cubierto");
        } else {
            inputTotalCoverage.setText("Faltan estaciones por cubrir," + " por favor selecciona la opcion de mostrar sugerencias" + "\n" + " para poder cubrir al 100% las sucursales");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea inputTotalCoverage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectBFSButton;
    private javax.swing.JButton selectDFSButton;
    // End of variables declaration//GEN-END:variables
}
