package com.interfaces;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import com.graph.LinkedList;
import com.graph.NetworkTrain;
import com.graph.PanelChangeListener;
import com.graph.Station;
import com.graph.StationLoadListener;
import com.graph.TValueListener;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class WelcomeInterface extends javax.swing.JFrame implements StationLoadListener, PanelChangeListener, TValueListener {

    private GUI gui;  // Instancia de GUI
    private boolean isGraphShown = false; // Variable para controlar si el grafo ha sido mostrado
    private NetworkTrain networkTrain; // Variablepara almacenar instancia de NetworkTrain
    private LinkedList<Station> stations; // Para almacenar estaciones cargadas
    private int tValue = -1; // Almacena el valor de T

    /**
     * Creates new form WelcomeInterface
     */
    public WelcomeInterface() {
        initComponents();
        // Inicializa NetworkTrain al crear la WelcomeInterface
        this.networkTrain = new NetworkTrain();

        if (isGraphShown) {
            Page1 p1 = new Page1(gui);
            ShowPanel(p1);
        }

    }

    private void ShowPanel(JPanel p) {
        p.setSize(389, 178);
        p.setLocation(0, 0);

        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    @Override
    public void onChangePanel(JPanel newPanel) {
        ShowPanel(newPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showGraphButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addStation = new javax.swing.JButton();
        totalCoverage = new javax.swing.JButton();
        deleteBranch = new javax.swing.JButton();
        setT = new javax.swing.JButton();
        branchCoverage = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome to Transmetropolis");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Options:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        showGraphButton.setText("Show Graph");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });
        jPanel1.add(showGraphButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 110, 30));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addStation.setText("Add Station");
        addStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStationActionPerformed(evt);
            }
        });
        jPanel2.add(addStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        totalCoverage.setText("Total Coverage");
        totalCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCoverageActionPerformed(evt);
            }
        });
        jPanel2.add(totalCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, -1));

        deleteBranch.setText("Delete Branch");
        deleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBranchActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, -1));

        setT.setText("Set T");
        setT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTActionPerformed(evt);
            }
        });
        jPanel2.add(setT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, -1));

        branchCoverage.setText("Branch Coverage");
        branchCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchCoverageActionPerformed(evt);
            }
        });
        jPanel2.add(branchCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 300));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 370, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void onStationsLoaded(LinkedList<Station> loadedStations) {
        // Aquí puedes manejar las estaciones cargadas
        // Por ejemplo, puedes guardarlas en una variable de instancia
        this.stations = loadedStations; // Asegúrate de tener un campo para guardar las estaciones en WelcomeInterface
    }

    @Override
    public void onTValueChanged(int newT) {
        this.tValue = newT;  // Almacena el valor T
        if (gui != null) {
            gui.setT(newT); // Actualiza el valor T en GUI
            // Si es necesario, aquí puedes llamar a gui.updateGraph();
            gui.updateGraph();
        }
    }


    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        // Verifica si tValue es -1 (no establecido)
        if (tValue == -1) {
            // Muestra un mensaje de error pidiendo al usuario que establezca T
            JOptionPane.showMessageDialog(this,
                    "Por favor, establezca un valor para T haciendo clic en el botón 'Set T'.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;  // Sale del método si T no está establecido
        }

        if (gui == null) {  // Solo crea la instancia una vez
            gui = new GUI(networkTrain);
            gui.addStationLoadListener(this); // Agrega el listener aquí
            gui.setT(tValue);  // Establece el valor T almacenado
        }

        if (!gui.isVisible()) {
            gui.setVisible(true);  // Asegúrate de que solo se abra si no está visible
        } else {
            gui.requestFocus();  // Si ya está abierta, tráela al frente
        }

    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void addStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStationActionPerformed
        try {
            checkNetworkLoaded();

            // Obtén la lista de sucursales desde GUI
            LinkedList<Station> branches = gui.getBranches();

            Page1 p1 = new Page1(gui);
            ShowPanel(p1);
        } catch (Exception e) {
            // Maneja el error si checkNetworkLoaded lanza una excepción
            JOptionPane.showMessageDialog(this,
                    "Error: La red no está cargada correctamente. Por favor, cargue la red antes de proceder.",
                    "Error de carga de red", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addStationActionPerformed

    private void totalCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCoverageActionPerformed
        try {
            checkNetworkLoaded();

            Page2 p2 = new Page2();
            ShowPanel(p2);
        } catch (Exception e) {
            // Maneja el error si checkNetworkLoaded lanza una excepción
            JOptionPane.showMessageDialog(this,
                    "Error: La red no está cargada correctamente. Por favor, cargue la red antes de proceder.",
                    "Error de carga de red", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_totalCoverageActionPerformed

    private void deleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBranchActionPerformed
        try {
            checkNetworkLoaded();

            // Obtén la lista de sucursales desde GUI
            LinkedList<Station> branches = gui.getBranches();

            // Pasa las sucursales a la interfaz Page3
            Page3 p3 = new Page3(gui);  // Le pasamos la lista de sucursales y la instancia de GUI
            ShowPanel(p3);  // Muestra la interfaz
        } catch (Exception e) {
            // Maneja el error si checkNetworkLoaded lanza una excepción
            JOptionPane.showMessageDialog(this,
                    "Error: La red no está cargada correctamente. Por favor, cargue la red antes de proceder.",
                    "Error de carga de red", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBranchActionPerformed

    private void setTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTActionPerformed

        Page4 p4 = new Page4(this);
        ShowPanel(p4);

    }//GEN-LAST:event_setTActionPerformed

    private void branchCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchCoverageActionPerformed
        try {
            // Verifica si la red está cargada correctamente
            checkNetworkLoaded();

            // Si la red está cargada, obten las branches
            LinkedList<Station> branches = gui.getBranches();

            // Crea y muestra el panel Page5 con los datos
            Page5 p5 = new Page5(gui, networkTrain, this);
            ShowPanel(p5);

        } catch (Exception e) {
            // Maneja el error si checkNetworkLoaded lanza una excepción
            JOptionPane.showMessageDialog(this,
                    "Error: La red no está cargada correctamente. Por favor, cargue la red antes de proceder.",
                    "Error de carga de red", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_branchCoverageActionPerformed

    //  Revisa si las estaciones estan cargadas 
    private void checkNetworkLoaded() {
//        if (gui == null) {
//            JOptionPane.showMessageDialog(this,
//                    "La red no ha sido cargada. Por favor, haga click en 'Show Graph' antes de continuar.",
//                    "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }

        if (gui.isNetworkLoaded()) {
            isGraphShown = true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStation;
    private javax.swing.JButton branchCoverage;
    private javax.swing.JPanel content;
    private javax.swing.JButton deleteBranch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton setT;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JButton totalCoverage;
    // End of variables declaration//GEN-END:variables
}
